import React from 'react';

export function OpenGraphMeta({ providerName, imageUrl, description }: { providerName: string, imageUrl: string, description?: string }) {
  return (
    <>
      <meta property="og:title" content={`Image generated by ${providerName}`} />
      <meta property="og:image" content={imageUrl} />
      <meta property="og:description" content={description || `See images generated by ${providerName} on CyberSecured AI.`} />
      <meta property="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={`Image generated by ${providerName}`} />
      <meta name="twitter:image" content={imageUrl} />
      <meta name="twitter:description" content={description || `See images generated by ${providerName} on CyberSecured AI.`} />
    </>
  );
}
