name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start server with mock adapter
        run: |
          nohup env ENABLE_MOCK_ADAPTER=true NODE_ENV=development AUTH0_CLIENT_SECRET=ci AUTH0_CLIENT_ID=ci AUTH0_DOMAIN=example.com PORT=5000 npm run dev > server.log 2>&1 &

      - name: Wait for server
        run: |
          for i in {1..20}; do
            if curl -sSf http://127.0.0.1:5000/api/health >/dev/null; then
              echo "server up"; break
            fi
            sleep 1
          done

      - name: Run smoke tests
        run: npm run test:smoke

      - name: Run unit tests
        run: npm test -- --run --reporter=dot
