name: Deploy client (Vite) to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (clean, reproducible)
        run: npm ci

      - name: Update Browserslist DB (optional)
        run: npx update-browserslist-db@latest || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Vite client (with fallback)
        run: |
          set -euxo pipefail
          # Show available scripts for debugging
          npm run || true
          if node -e "const p=require('./package.json'); process.exit(p.scripts && p.scripts['build:client']?0:1)"; then
            npm run build:client
          elif node -e "const p=require('./package.json'); process.exit(p.scripts && p.scripts['build']?0:1)"; then
            npm run build
          else
            npx vite build
          fi

      - name: Prepare site artifact (dist/public)
        run: |
          set -euxo pipefail
          mkdir -p _site
          rsync -a --delete dist/public/ _site/
          # Include custom domain if present
          if [ -f CNAME ]; then cp CNAME _site/CNAME; fi
          # SPA fallback for deep links
          if [ -f _site/index.html ] && [ ! -f _site/404.html ]; then cp _site/index.html _site/404.html; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
